---
regions:
  - us-west-1

blocklist:
  - "131049215162"
  - "244701641490"
  - "231978183061"
  - "116307690747"
  - "047239926301"
  - "030896613128"
  - "073107683589"
  - "354918377608"
  - "385011339517"
  - "265519291241"
  - "036890096944"
  - "238518560584"
  - "094304803586"
  - "189544134327"
  - "224204046505"
  - "062924565464"
  - "164534504923"
  - "134475524490"
  - "253563727619"
  - "610374263658"
  - "430515702528"
  - "563957789558"
  - "544504789502"
  - "429441945002"
  - "492370087908"
  - "472191836101"
  - "474668416230"
  - "508284831906"
  - "430118830268"
  - "646510057038"
  - "404410098344"
  - "546477759576"
  - "648518523462"
  - "547021456316"
  - "669633639293"
  - "699978261721"
  - "504956989533"
  - "469439403837"
  - "662491802882"
  - "874282554547"
  - "992382389386"
  - "999820109120"
  - "920373021948"
  - "754984507865"
  - "842446586533"
  - "748325219294"
  - "951861692570"
  - "857532383661"
  - "780835626986"
  - "918220515115"
  - "710190935322"
  - "767397730891"
  - "783764602818"
  - "767397952381"

accounts:
  "078963965848":
    filters:
      __global__:
        - type: tag
          key: GitHubRunID
          value: "PLACEHOLDER_RUN_ID"
